# Generated by Django 3.2.5 on 2021-07-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('rating', models.IntegerField(blank=True)),
                ('courtQty', models.IntegerField()),
                ('material', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
